### ISSUE TITLE
get (or generate) an image for meta image stuff for social media???

### ISSUE THREAD

**Issue by ninjamuffin99** [FunkinCrew/funkBlog#11]
This will be for use when sharing to social media, discord, etc.

For example: when sharing a github link, it will give you a nice cute image within the embed
<img width="624" alt="image" src="https://github.com/FunkinCrew/funkBlog/assets/22229331/2134bdb4-1e2e-4234-9bbc-2e76acf7830c">

Status right now, I'd have to look into seeing if it's possible to generate something via zola directly, otherwise... might need to use some NPM thing... like [Sharp](https://sharp.pixelplumbing.com/) (which might also give the benefit of having a bit more of a crossplatform solution, if we swap sites...)

**Comment by BombasticTom** [comment]
what

**Comment by ninjamuffin99** [comment]
https://ahrefs.com/blog/open-graph-meta-tags/

**Comment by BombasticTom** [comment]
is this embedding for stuff like twitter and discord?

**Comment by ninjamuffin99** [comment]
yes exactly 🙂

**Comment by BombasticTom** [comment]
holy shit!! thats crazy.

**Comment by ember-ana** [comment]
implemented in v2

**Comment by BombasticTom** [comment]
Wowie Zowie! Lesgoo
