### ISSUE TITLE
Images not loading | Usage of Discord's CDN

### ISSUE THREAD

**Issue by Sapphiku** [FunkinCrew/funkBlog#28]
In the latest Funkin' blog, two images at the beginning (dated 2024/03/12) fail to load and display an error message: "This content is no longer available."
![image](https://github.com/FunkinCrew/funkBlog/assets/149914478/c58fcd85-e315-4f50-aa76-33db0709eaf0)
![image](https://github.com/FunkinCrew/funkBlog/assets/149914478/a38e7e59-abc6-4e32-891e-7e64de60d589)

The reason behind this is likely due to Discord's CDN change to prevent malicious acts, such as hosting malware and what not, which that can be read about [here](https://www.bitdefender.com/blog/hotforsecurity/discord-tightens-security-with-temporary-file-links/), or it could be due to the images being deleted (though that's probably not the case).

Unfortunately, there isn't much I can do to fix this problem directly. However, there are some solutions, such as hosting the missing files on funkin.me's site instead, which that's a really great alternative instead of relaying solely on Discord.

**Comment by ninjamuffin99** [comment]
should be closed with #27 !
